#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import platform_egl_builders

common_egl = [
    "context_gl_egl.cpp",
    "crash_handler_egl.cpp",
    "os_egl.cpp",
    "key_mapping_egl.cpp",
    "joypad_linux.cpp",
    "power_egl.cpp",
    "detect_prime.cpp",
]

if "udev" in env and env["udev"]:
    common_egl.append("libudev-so_wrap.c")

prog = env.add_program("#bin/godot", ["godot_egl.cpp"] + common_egl)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(platform_egl_builders.make_debug_egl))
